smarthealth/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('password-reset/', PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('api-auth/', include('rest_framework.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import UserRegistration, load_districts, load_thanas, home, UserLoginView, dashboard, DoctorRegistration, activate, PatientDetailView, search, BookingCreateView, VoterIDAPI, BmaAPI, ProfileView, ScheduleCreateView, ScheduleUpdateView, TreatmentCreateView, searchpatient, PrescriptionView, ReportCreateView, DoctorDetailView, ReportUpdateView, UserUpdateView, DoctorUpdateView, CreateOTPView, check_otp, OtpAPI, UserExUpdateView, DoctorExUpdateView, payment, complete, CreateDoctorOTPView, check_otp_doctor, CommentCreateView, reg
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', home, name='home'),
    path('register/', reg, name='register'),
    # path('', UserLoginView.as_view(), name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('search/', search, name='search'),
    path('search/patient', searchpatient, name='search-patient'),
    path('schedule/<int:pk>/create/', ScheduleCreateView.as_view(), name='schedule-create'),
    path('schedule/<int:pk>/update/', ScheduleUpdateView.as_view(), name='schedule-udpate'),
    path('user/register', UserRegistration.as_view(), name='user-reg'),
    path('user/<int:pk>/update/', UserUpdateView.as_view(), name='user-update'),
    path('user/<int:pk>/update/ex', UserExUpdateView.as_view(), name='user-update-ex'),
    path('doctor/<int:pk>/update/', DoctorUpdateView.as_view(), name='doctor-update'),
    path('doctor/<int:pk>/update/ex', DoctorExUpdateView.as_view(), name='doctor-update-ex'),
    path('user/<int:pk>/profile/', ProfileView.as_view(), name='user-profile'),
    path('user/otp/', CreateOTPView.as_view(), name='otp-gen'),
    path('user/<int:pk>/otp/', CreateDoctorOTPView.as_view(), name='otp-gen-doctor'),
    path('user/otp/confirm/', check_otp, name='otp-check'),
    path('user/<int:pk>/otp/confirm/', check_otp_doctor, name='otp-check-doctor'),
    path('doctor/register', DoctorRegistration.as_view(), name='doctor-reg'),
    path('ajax/load-district/', load_districts, name='ajax_load_districts'),
    path('ajax/load-thana/', load_thanas, name='ajax_load_thanas'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('user/patient/<int:pk>/', PatientDetailView.as_view(), name='patient-view'),
    path('user/doctor/<int:pk>/', DoctorDetailView.as_view(), name='doctor-view'),
    path('user/patient/<int:pk>/treatment/create/', TreatmentCreateView.as_view(), name='treatment-create'),
    path('<int:pk>/consult/', BookingCreateView.as_view(), name='consult'),
    path('api/voter-id/', VoterIDAPI.as_view(), name='voter-id'),
    path('api/bma/', BmaAPI.as_view(), name='bma'),
    path('api/otp/', OtpAPI.as_view(), name='otp-api'),
    path('treatment/<int:pk>/', PrescriptionView.as_view(), name='treatment-details'),
    path('treatment/<int:pk>/report/upload', ReportCreateView.as_view(), name='report-create'),
    path('treatment/<int:pk>/report/update', ReportUpdateView.as_view(), name='report-update'),
    path('report/<int:pk>/comment/add', CommentCreateView.as_view(), name='comment-create'),
    path('payment/', payment, name='payment'),
    path('payment/complete', complete, name='payment-status'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

def upload_directory(instance, filename):
    return f"report/{instance.treatment.patient.sn}/{filename}"

class Division(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class District(models.Model):
    division = models.ForeignKey(Division, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    
    def __str__(self):
        return self.name

class Thana(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name

class Speciality(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class User(AbstractUser):
    USER_TYPE_CHOICES = (
        (1, 'admin'),
        (2, 'doctor'),
        (3, 'patients'),
        (4, 'Manager'),
    )
    VERIFY_STATUS = (
        ('yes', 'yes'),
        ('no', 'no')
    )

    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    BG_CHOICES = (
        ('O+', 'O+'),
        ('O-', 'O-'),
        ('A+', 'A+'),
        ('A-', 'A-'),
        ('B+', 'B+'),
        ('B-', 'B-'),
        ('AB+', 'AB+'),
        ('AB-', 'AB-'),
    )

    DESIGNATION_CHOICES = (
        ('Professor', 'Professor'), 
	    ('Associate Professor', 'Associate Professor'),
	    ('Assistant Professor', 'Assistant Professor'),
        ('Consultant', 'Consultant'),
	    ('Registras', 'Registras'),
	    ('Assistant Registras', 'Assistant Registras'),
	    ('IMO', 'IMO'),
        ('EMO', 'EMO'),
        ('RMO', 'RMO'),
        ('HMO', 'HMO'),
        ('Other', 'Other')
    )

    username = None
    sn = models.CharField(verbose_name='Serial Number', max_length=12, unique=True, error_messages={'required': 'Your Name is Required'})
    pm_division = models.ForeignKey(Division, verbose_name='Division', related_name='pm_division', on_delete=models.DO_NOTHING, null=True, blank=True)
    pm_district = models.ForeignKey(District, verbose_name='District', related_name='pm_district', on_delete=models.DO_NOTHING, null=True, blank=True)
    pm_thana = models.ForeignKey(Thana, verbose_name='Thana', related_name='pm_thana', on_delete=models.DO_NOTHING, null=True, blank=True)
    ps_division = models.ForeignKey(Division, verbose_name='Division', related_name='ps_division', on_delete=models.DO_NOTHING, null=True, blank=True)
    ps_district = models.ForeignKey(District, verbose_name='District', related_name='ps_district', on_delete=models.DO_NOTHING, null=True, blank=True)
    ps_thana = models.ForeignKey(Thana, verbose_name='Thana', related_name='ps_thana', on_delete=models.DO_NOTHING, null=True, blank=True)
    pm_village = models.CharField(verbose_name='Village',max_length=50, null=True, blank=True)
    ps_village = models.CharField(verbose_name='Village',max_length=50, null=True, blank=True)
    pm_union = models.CharField(verbose_name='Union',max_length=50, null=True, blank=True)
    ps_union = models.CharField(verbose_name='Union',max_length=50, null=True, blank=True)
    pm_ward = models.CharField(verbose_name='Ward',max_length=50, null=True, blank=True)
    ps_ward = models.CharField(verbose_name='Ward',max_length=50, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    image = models.ImageField(default='default.jpg', upload_to='users', null=True, blank=True)
    verified = models.CharField(max_length=10, choices=VERIFY_STATUS, null=True, default='no')
    user_type = models.PositiveIntegerField(choices=USER_TYPE_CHOICES, default=3, blank=True, null=True)
    mobile = models.CharField(verbose_name='Mobile Number', max_length=11, blank=True)
    payment = models.CharField(verbose_name='Payment Number', max_length=11, null=True, blank=True)
    nid = models.CharField(verbose_name='National ID', max_length=10, blank=True, null=True)
    bma = models.CharField(verbose_name='BMA Code', max_length=20, blank=True, null=True)
    institute = models.CharField(verbose_name='Institute', max_length=100, blank=True, null=True)
    designation = models.CharField(verbose_name='Designation', max_length=50, choices=DESIGNATION_CHOICES, blank=True, null=True)
    specialist = models.ForeignKey(Speciality, verbose_name='Specialist', blank=True, null=True, on_delete=models.CASCADE)
    father_name = models.CharField(verbose_name='Father\'s name', max_length=25, null=True, blank=True)
    mother_name = models.CharField(verbose_name='Mother\'s name', max_length=25, null=True, blank=True)
    father_mobile = models.CharField(verbose_name='Father\'s Mobile', max_length=11, null=True, blank=True)
    mother_mobile = models.CharField(verbose_name='Mother\'s Mobile', max_length=11, null=True, blank=True)
    bg = models.CharField(verbose_name='Blood Group', max_length=11, choices=BG_CHOICES, null=True, blank=True)
    gender = models.CharField(verbose_name='Select Gender', max_length=11, choices=GENDER_CHOICES, null=True, blank=True)


    USERNAME_FIELD = 'sn'
    # REQUIRED_FIELDS = []

    def __str__(self):
        return self.sn


class Schedule(models.Model):
    DAYS = (
        ('Sunday', 'Sunday'),
        ('Monday', 'Monday'),
        ('Tuesday', 'Tuesday'),
        ('Wednessday', 'Wednessday'),
        ('Thursday', 'Thursday'),
        ('Friday', 'Friday'),
        ('Saturday', 'Saturday'),
    )
    name = models.CharField(verbose_name='Place', max_length=200, null=True)
    wkfrom = models.CharField(verbose_name='Start Day', max_length=15, choices=DAYS)
    wkto = models.CharField(verbose_name='End day', max_length=15, choices=DAYS)
    timefrom = models.TimeField(verbose_name='Time From', null=True)
    timeto = models.TimeField(verbose_name='Time To', null=True)
    fee = models.CharField(verbose_name='Consultaiton Fee', max_length=20)
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class VoterID(models.Model):
    voter_id = models.CharField(max_length=10)

    def __str__(self):
        return self.voter_id

class BMA(models.Model):
    code = models.CharField(max_length=10)
    institute = models.CharField(max_length=100)

    def __str__(self):
        return self.code

class Treatment(models.Model):
    patient = models.ForeignKey(User, related_name='treatment_patient', on_delete=models.CASCADE)
    doctor = models.ForeignKey(User, related_name='treatment_doctor', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    date = models.DateField(auto_now_add=True, blank=True, null=True)
    prescription = models.TextField()

    def __str__(self):
        return self.title

class Test(models.Model):
    treatment = models.ForeignKey(Treatment, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100, null=True, verbose_name="Report Title")
    reportimg = models.ImageField(upload_to=upload_directory, verbose_name="Upload Report Scanned Image", default='default.jpg', blank=True)
    reportpdf = models.FileField(upload_to=upload_directory, verbose_name="Upload Report Scanned PDF", default='default.pdf', blank=True)

    def __str__(self):
        return f"{self.title}"

class Comment(models.Model):
    report = models.ForeignKey(Test, blank=True, null=True, on_delete=models.CASCADE)
    comment = models.TextField(verbose_name='Write your comments')
    doctor = models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return f"{self.report.title}'s Comment"

class Payment(models.Model):
    PAYMENT_METHOD_CHOICES = (
        ('bKash', 'bKash'),
        ('Rocket', 'Rocket'),
        ('Nagad', 'Nagad'),
        ('DBBL', 'DBBL'),
        ('Skrill', 'Skrill'),
        ('Aqua', 'Aqua')
    )

    STATUS_OPTION_CHOICES = (
        ('Approved', 'Approved'),
        ('Pending', 'Pending')
    )

    trxnid = models.CharField(max_length=50)
    amount = models.FloatField('Paid Amount', default=0)
    payment_method = models.CharField(max_length=6, choices=PAYMENT_METHOD_CHOICES, default='bKash')
    payment_date = models.DateField(null=True)
    treatment = models.ForeignKey(Treatment, on_delete=models.DO_NOTHING)
    doctor = models.ForeignKey(User, related_name='booking_doctor', on_delete=models.CASCADE, null=True, blank=True)
    status = models.CharField(max_length=8, choices=STATUS_OPTION_CHOICES, default='Pending', null=True, blank=True)

    def __str__(self):
        return self.trxnid

class OTP(models.Model):
    number = models.CharField(max_length=100, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.number

users/templates/users/district.html
<option value="">Select District</option>
{% for district in districts %}
<option value="{{ district.pk }}">{{ district.name }}</option>
{% endfor %}

users/templates/users/doctor_reg.html
{% extends 'users/dashboard/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h3 class="text-center text-warning">Doctor Registration</h3>
    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
    <div class="my-5">
        <form action="" method="POST" id="regForm" class="w-75 mx-auto p-5 shadow" style="background-color: #eee;" enctype="multipart/form-data" data-districts-url="{% url 'ajax_load_districts' %}" data-thanas-url="{% url 'ajax_load_thanas' %}" novalidate>
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    {{ form.first_name|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.last_name|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.sn|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form.nid|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.mobile|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.birthday|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form.image|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.gender|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.bg|as_crispy_field }}
                </div>
            </div>
            <br>
            <fieldset class="border p-2">
                <legend class="w-auto">Family Details</legend>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.father_name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.father_mobile|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.mother_name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.mother_mobile|as_crispy_field }}
                    </div>
                </div>
            </fieldset>
            <fieldset class="border p-2">
                <legend class="w-auto">Present Address</legend>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.ps_division|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.ps_district|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.ps_thana|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.ps_union|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.ps_ward|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.ps_village|as_crispy_field }}
                    </div>
                </div>
            </fieldset>
            <fieldset class="border p-2">
                <legend class="w-auto">Permanent Address</legend>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.pm_division|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.pm_district|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.pm_thana|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.pm_union|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.pm_ward|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.pm_village|as_crispy_field }}
                    </div>
                </div>
            </fieldset>
            <fieldset class="border p-2">
                <legend class="w-auto">Doctor Info</legend>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.bma|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.payment|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.specialist|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.designation|as_crispy_field }}
                    </div>
                </div>
            </fieldset>
            <br>
            <div class="row">
                <div class="col-md-6">
                    {{ form.password1|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.password2|as_crispy_field }}
                </div>
            </div>
            {{ form.verified|as_crispy_field }}
            {{ form.institute|as_crispy_field }}
            <br>
            <button type="submit" class="btn btn-success submit">Sign Up</button>
        </form>
    </div>
    {% endblock content %}
    
    <!-- <script>
        $( function() {
          $( "#id_birthday" ).datepicker();
        } );
    </script> -->
    {% block script %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
    <script>
        $("#id_pm_division").change(function (){
            var url = $("#regForm").attr("data-districts-url");
            var divisionId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'pm_division': divisionId
                },
                success: function (data){
                    $("#id_pm_district").html(data);
                }
            });
        });
        $("#id_pm_district").change(function (){
            var url = $("#regForm").attr("data-thanas-url");
            var districtId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'pm_district': districtId
                },
                success: function (data){
                    $("#id_pm_thana").html(data);
                }
            });
        });

        $("#id_ps_division").change(function (){
            var url = $("#regForm").attr("data-districts-url");
            var divisionId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'ps_division': divisionId
                },
                success: function (data){
                    $("#id_ps_district").html(data);
                }
            });
        });
        $("#id_ps_district").change(function (){
            var url = $("#regForm").attr("data-thanas-url");
            var districtId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'ps_district': districtId
                },
                success: function (data){
                    $("#id_ps_thana").html(data);
                }
            });
        });
    </script>
    <script>
        // const date = document.getElementById('id_mobile');
        const date = document.getElementById('id_birthday')
        const sn = document.getElementById('id_sn')
        
        date.addEventListener('change', () => {
            let dv = date.value.split("-").join("");
            let rand = []
            for(let i=0; i<4;i++){
                rand.push(Math.floor(Math.random()*10));
            }
            rand = rand.join("")
            sn.value = dv+rand;
        })
        console.log(sn.value)
    </script>
    {% endblock script %}

users/templates/users/doctor_update.html
{% extends 'users/dashboard/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h3 class="text-center text-warning">Doctor Update</h3>
    {% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}
    <div class="row my-5">
        <form action="" method="POST" class="w-75 mx-auto p-5 shadow" style="background-color: #eee;" id="regForm" enctype="multipart/form-data" data-districts-url="{% url 'ajax_load_districts' %}" data-thanas-url="{% url 'ajax_load_thanas' %}" novalidate>
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6">
                    {{ form.first_name|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.last_name|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="col-md-6">
                    {{ form.sn|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form.nid|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.mobile|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.birthday|as_crispy_field }}
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    {{ form.image|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.gender|as_crispy_field }}
                </div>
                <div class="col-md-4">
                    {{ form.bg|as_crispy_field }}
                </div>
            </div>
            <br>
            <fieldset class="border p-2">
                <legend class="w-auto">Family Details</legend>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.father_name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.father_mobile|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.mother_name|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.mother_mobile|as_crispy_field }}
                    </div>
                </div>
            </fieldset>
            <fieldset class="border p-2">
                <legend class="w-auto">Present Address</legend>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.ps_division|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.ps_district|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.ps_thana|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.ps_village|as_crispy_field }}
                    </div>
                </div>
            </fieldset>
            <br>
            <fieldset class="border p-2">
                <legend class="w-auto">Permanent Address</legend>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.pm_division|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.pm_district|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.pm_thana|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.pm_village|as_crispy_field }}
                    </div>
                </div>
            </fieldset>
            <br>
            <fieldset class="border p-2">
                <legend class="w-auto">Doctor Info</legend>
                <div class="row">
                    <div class="col-md-6">
                        {{ form.bma|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.payment|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.specialist|as_crispy_field }}
                    </div>
                    <div class="col-md-6">
                        {{ form.designation|as_crispy_field }}
                    </div>
                </div>
            </fieldset>
            <br>
            
            <br>
            <button type="submit" class="btn btn-success submit">Update Account</button>
            <a href="{% url 'user-profile' request.user.id %}" class="btn btn-warning">Back To Profile</a>
        </form>
    </div>
    {% endblock content %}
    
    <!-- <script>
        $( function() {
          $( "#id_birthday" ).datepicker();
        } );
    </script> -->
    {% block script %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30=" crossorigin="anonymous"></script>
    <script>
        $("#id_pm_division").change(function (){
            var url = $("#regForm").attr("data-districts-url");
            var divisionId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'pm_division': divisionId
                },
                success: function (data){
                    $("#id_pm_district").html(data);
                }
            });
        });
        $("#id_pm_district").change(function (){
            var url = $("#regForm").attr("data-thanas-url");
            var districtId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'pm_district': districtId
                },
                success: function (data){
                    $("#id_pm_thana").html(data);
                }
            });
        });

        $("#id_ps_division").change(function (){
            var url = $("#regForm").attr("data-districts-url");
            var divisionId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'ps_division': divisionId
                },
                success: function (data){
                    $("#id_ps_district").html(data);
                }
            });
        });
        $("#id_ps_district").change(function (){
            var url = $("#regForm").attr("data-thanas-url");
            var districtId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    'ps_district': districtId
                },
                success: function (data){
                    $("#id_ps_thana").html(data);
                }
            });
        });
    </script>
    <script>
        // const date = document.getElementById('id_mobile');
        const date = document.getElementById('id_birthday')
        const sn = document.getElementById('id_sn')
        
        date.addEventListener('change', () => {
            let dv = date.value.split("-").join("");
            let rand = []
            for(let i=0; i<4;i++){
                rand.push(Math.floor(Math.random()*10));
            }
            rand = rand.join("")
            sn.value = dv+rand;
        })
        console.log(sn.value)
    </script>
    {% endblock script %}

users/templates/users/otp_mail.html
{% autoescape off %}  
Hi {{ user.first_name }} {{ user.last_name }},
Your LOGIN ID is : {{ user.sn }}
OTP : {{ otp }}
Please Type the Otp on the form to access update.
If you think, it's not you, then just ignore this email.  
{% endautoescape %}

users/templates/users/password_reset.html
{% extends 'users/dashboard/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="my-5">
    <form method="POST" class="my-5 p-5 w-75 mx-auto shadow" style="background-color: #eee;">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
        </div>
    </form>
</div>

{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'users/dashboard/base.html' %}
{% block content %}

<div class="my-5 w-75 mx-auto">
    <div class="alert alert-info">
        An email has been sent with instructions to reset your password
    </div>
</div>

{% endblock content %}